my problem? 1) Won't work for 2nd or 3rd reply  Uncaught (in promise) TypeError: callbacks[i2].apply is not a function  2) Join garda, unresponsive kaile kai
 3) load garda, first join form ko dekhaucha(joined = false condition) ani once the state is fetched, Joined= true ko dekhaucha, Instead of that, do a loading screen or somehting, later.
 4) Firefox can’t establish a connection to the server at ws://localhost:3000/socket.io/?EIO=4&transport=websocket&sid=i3x6FsXzgOQ4F3k5AALF.
 Connection nai chait bhaidine..

 5) client id keeps changing, so can't implement this:
     client.broadcast.emit('typing', { name, isTyping });

     These are the problems faced when doing socket implementation. ONce a headache, always a headache.

     Solution:
     1) Consistent connection, will solve, 4 and 5, so that there will be consistent client id, which will give me a running code.

 So, to do list, read about webscokets from enst js documentation and go throught other's code